### ISSUE TITLE
1.18.2-67 -- 'patchouli-client.toml is not correct. Correcting' log spam

### ISSUE THREAD

**Issue by hanleybrand** [VazkiiMods/Patchouli#547]
### Mod loader

Forge

### Minecraft version

1.18.2

### Patchouli version

1.18.2-67.jar

### Modloader version

40.1.16

### The latest.log file

https://gist.github.com/hanleybrand/8779f6bcfebe6f35041cac6a9d31ec85

### Issue description

Log spammed with message (multiple times per second)

> Configuration file ˜/Library/Application Support/ManyMC/instances/1.18.2/.minecraft/config/patchouli-client.toml is not correct. Correcting

### Steps to reproduce

1. Start single player world
2. Read log?

It's unclear if this is having any effect on the game outside of the log messages

### Other information

There was a previous issue #508 with the same symptom that was closed, marked completed because the bug was fixed (not sure if something was refactored and the bug resurfaced, but it has been manifesting over the last couple 18.2/forge patchouli releases)

**Comment by hanleybrand** [comment]
For reference, here's the (default, unedited) patchouli-client.toml file from my config folder:

```toml
#Set this to true to disable advancement locking for ALL books, making all entries visible at all times. Config Flag: advancements_disabled
disableAdvancementLocking = false
#Granular list of Book ID's to disable advancement locking for, e.g. [ "botania:lexicon" ]. Config Flags: advancements_disabled_<bookid>
noAdvancementBooks = []
#Enable testing mode. By default this doesn't do anything, but you can use the config flag in your books if you want. Config Flag: testing_mode
testingMode = false
#Set this to the ID of a book to have it show up in players' inventories, replacing the recipe book.
inventoryButtonBook = ""
#Set this to true to use Shift instead of Ctrl for the inventory quick lookup feature.
useShiftForQuickLookup = false
#Set how text overflow should be coped with: overflow the text off the page, truncate overflowed text, or resize everything to fit. Relogin after changing.
#Allowed Values: OVERFLOW, TRUNCATE, RESIZE
textOverflowMode = "RESIZE"
```
